text = input("enter text to write to the file:")
file_header = open("outpt.txt",'w')
file_header.write(text + '\n')
file_header.close()
print("data successsfully writen to outpt.txt")
additional_text = input("Enetr additional testt append:")
file_header= open("outpt.txt","a")
file_header.write(additional_text + "\n")
file_header.close()
print("data succesfully appended")
file_header = open("outpt.txt","r")
contents = file_header.read()
file_header.close()
print("\nfinal content of outpt.txt:")
print(contents)

